config/routes.rb
Rails.application.routes.draw do
  resources :seeds
  resources :crops
  get 'trending/index'
  resources :infos
  resources :events

  root 'home#homepage'
  
  mount ActionCable.server => '/cable'

  resources :notifications

  resources :tools

  resources :tasks


  devise_for :users

  resources :users_profiles, only: [:edit, :update]
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get 'home/homepage'

  get '/about', to:'home#about'
  get '/myprofile', to:'users_profiles#show'

  get '/mylistings', to:'tasks#my_tasks'
  get '/mylistings1', to:'tools#my_tools'
 
  get '/search/results', to: 'search#results'

  get '/trending', to: 'trending#index'

 

  get '/calendar', to: 'events#new'

  get 'message/index'

  get 'listings/mylistings'



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/crop.rb
class Crop < ApplicationRecord
  belongs_to :user
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
end

app/models/info.rb
class Info < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :task,optional: true
  belongs_to :tool,optional: true


  def self.notice

    expiry_tools = Tool.where("todate = ?", Date.tomorrow)
  
    expiry_tools.each do |tool|

    requester = Notification.find_by(user_id: tool.user_id)


     Notification.create!(
        user_id: requester.requester_id,
        content: "#{tool.toolname} you borrowd needs to be returned tommorow.",
        status: "pending",
        tool_id: tool.id,
        requester_id: tool.user_id
      )
     
      Notification.create!(
        user_id: tool.user_id,
        content: "#{tool.toolname} you rented out needs to be collected tomorrow.",
        status: "pending",
        tool_id: tool.id,
        requester_id:requester.requester_id
      )

puts 'notification sent'
    
 
    end
  end

end

app/models/region.rb
class Region < ApplicationRecord
end

app/models/seed.rb
class Seed < ApplicationRecord
  belongs_to :user
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  has_many :notifications 
end

app/models/tool.rb
class Tool < ApplicationRecord
  belongs_to :user
  has_many :notifications 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   has_one_attached :profile_picture
   
has_many :tasks

has_many :tools

has_many :notifications

has_many :messages
has_many :events

has_many :seeds
has_many :crops

   validates :name, :email, :phone_number, presence: true
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  before_action :set_tool, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /tools or /tools.json
  def index
    @tools = Tool.all
    @tool_usernames = {}
    @notification = Notification.new
  
    @tools.each do |tool|
      user = User.find_by(id: tool.user_id)
      @tool_usernames[tool.id] = user.name if user
    end
  end

  def my_tools 
    @mytools = current_user.tools
  end


  # GET /tools/1 or /tools/1.json
  def show
  end

  # GET /tools/new
  def new
    @tool = Tool.new
  end

  # GET /tools/1/edit
  def edit
  end

  # POST /tools or /tools.json
  def create
    @tool = Tool.new(tool_params)
    @tool.user_id=current_user.id

    respond_to do |format|
      if @tool.save
        format.html { redirect_to tool_url(@tool), notice: "Tool was successfully created." }
        format.json { render :show, status: :created, location: @tool }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tool.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tools/1 or /tools/1.json
  def update
    respond_to do |format|
      if @tool.update(tool_params)
        format.html { redirect_to tool_url(@tool), notice: "Tool was successfully updated." }
        format.json { render :show, status: :ok, location: @tool }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tool.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tools/1 or /tools/1.json
  def destroy
    @tool.destroy

    respond_to do |format|
      format.html { redirect_to tools_url, notice: "Tool was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tool
      @tool = Tool.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tool_params
      params.require(:tool).permit(:toolname, :fromdate, :todate, :no_tools, :cost, :location, :user_id)
    end
end

app/helpers/crops_helper.rb
module CropsHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/seeds_helper.rb
module SeedsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/helpers/trending_helper.rb
module TrendingHelper
end

app/views/tools/_form.html.erb
<%= stylesheet_link_tag "style_1" %>

  <div class="p-5 my-4 bg-body-tertiary rounded-3">
    <div class="container-fluid py-5 px-5 my-2 my-form">
      <h1 class="display-5 fw-bold text-success text-center"> Tool Listing</h1>
      <%= form_with(model: tool, class: "form" ) do |form| %>
        <% if tool.errors.any? %>
          <div class="alert alert-danger">
            <h2>
              <%= pluralize(tool.errors.count, "error" ) %> prohibited this tool from being saved:
            </h2>
            <ul>
              <% tool.errors.each do |error| %>
                <li>
                  <%= error.full_message %>
                </li>
                <% end %>
            </ul>
          </div>
          <% end %>
            <div class="mb-3">
              <%= form.label :toolname, "Tool Name" , class: "form-label" %>
                <%= form.text_field :toolname, class: "form-control" %>
            </div>
            <div class="mb-3">
              <%= form.label :fromdate, "From Date" , class: "form-label" %>
                <%= form.date_field :fromdate, class: "form-control" %>
            </div>
            <div class="mb-3">
              <%= form.label :todate, "To Date" , class: "form-label" %>
                <%= form.date_field :todate, class: "form-control" %>
            </div>
            <div class="mb-3">
              <%= form.label :no_tools, "Number of Tools" , class: "form-label" %>
                <%= form.number_field :no_tools, class: "form-control" %>
            </div>
                <div class="mb-3">
              <%= form.label :location, "Location" , class: "form-label" %>
                <%= form.text_field :location, class: "form-control" %>
            </div>
            <div class="mb-3">
              <%= form.label :cost, "Cost" , class: "form-label" %>
                <%= form.number_field :cost, class: "form-control" %>
            </div>
            <%= form.hidden_field :user_id %>
              <div class="mb-3">
                <%= form.submit "List Tool" , class: "btn btn-success" %>
              </div>
              <% end %>
    </div>
  </div>

app/views/tools/_tool.html.erb
<div id="<%= dom_id tool %>">
  <p>
    <strong>Toolname:</strong>
    <%= tool.toolname %>
  </p>

  <p>
    <strong>Fromdate:</strong>
    <%= tool.fromdate %>
  </p>

  <p>
    <strong>Todate:</strong>
    <%= tool.todate %>
  </p>

  <p>
    <strong>No tools:</strong>
    <%= tool.no_tools %>
  </p>

  <p>
    <strong>Cost:</strong>
    <%= tool.cost %>
  </p>

    <p>
    <strong>Location:</strong>
    <%= tool.location %>
  </p>

  <p>
    <strong>User:</strong>
    <%= tool.user_id %>
  </p>

</div>

app/views/tools/edit.html.erb
<div class="p-5 my-4 bg-body-tertiary rounded-3">
  <div class="container-fluid py-5 px-5 my-2 my-form">
    <h1 class="display-5 fw-bold text-success text-center">Edit Tool</h1>
    <%= form_with(model: @tool, class: "form" ) do |form| %>
      <% if @tool.errors.any? %>
        <div class="alert alert-danger">
          <h2>
            <%= pluralize(@tool.errors.count, "error" ) %> prohibited this tool from being saved:
          </h2>
          <ul>
            <% @tool.errors.each do |error| %>
              <li>
                <%= error.full_message %>
              </li>
              <% end %>
          </ul>
        </div>
        <% end %>
          <div class="mb-3">
            <%= form.label :toolname, "Tool Name" , class: "form-label" %>
              <%= form.text_field :toolname, class: "form-control" %>
          </div>
          <div class="mb-3">
            <%= form.label :fromdate, "From Date" , class: "form-label" %>
              <%= form.text_field :fromdate, class: "form-control" , value: Date.today %>
          </div>
          <div class="mb-3">
            <%= form.label :todate, "To Date" , class: "form-label" %>
              <%= form.text_field :todate, class: "form-control" , value: Date.today %>
          </div>
          <div class="mb-3">
            <%= form.label :no_tools, "Number of Tools" , class: "form-label" %>
              <%= form.number_field :no_tools, class: "form-control" %>
          </div>
            <div class="mb-3">
              <%= form.label :location, "Location" , class: "form-label" %>
                <%= form.text_field :location, class: "form-control" %>
            </div>
          <div class="mb-3">
            <%= form.label :cost, "Cost" , class: "form-label" %>
              <%= form.number_field :cost, class: "form-control" %>
          </div>
          <%= form.hidden_field :user_id %>
            <div class="mb-3">
              <%= form.submit "Update Tool" , class: "btn btn-primary" %>
            </div>
            <% end %>
  </div>
</div>
<div>
  <%= link_to "Show this tool" , @tool %> |
    <%= link_to "Back to tools" , tools_path %>
</div>

app/views/tools/index.html.erb
<div class="container" style="margin-top: 100px">
  <div class="row mt-2">
    <% @tools.each do |tool| %>
      <div class="col-md-4 mb-4">
        <div class="card" style="background-color: #d6e6d6; max-width: 500px; margin: 0 auto">
          <div class="card-body" style="min-height: 310px">
            <h3 class="card-title">
              <%= tool.toolname %>
            </h3>
            <p class="card-text">
              <strong>Owner:</strong>
              <%= @tool_usernames[tool.id] %>
            </p>
            <p class="card-text">
              <strong>Available From:</strong>
              <%= tool.fromdate %>
            </p>
            <p class="card-text">
              <strong>Available Till:</strong>
              <%= tool.todate %>
            </p>

            <p class="card-text"><strong>Cost:</strong> ₹<%= tool.cost %>
            </p>

                <p class="card-text">
              <strong>Location:</strong>
              <%= tool.location %>
            </p>

            <% if tool.no_tools>0 %>
              <p class="card-text">
                <strong>Number of Tools:</strong>
                <%= tool.no_tools %>
              </p>

              <% if !(current_user.name==@tool_usernames[tool.id]) %>
                <%= form_with(model: @notification) do |form| %>
                  <% if @notification.errors.any? %>
                    <div style="color: red">
                      <h2>
                        <%= pluralize(@notification.errors.count, "error" ) %> prohibited
                          this notification from being saved:
                      </h2>

                      <ul>
                        <% @notification.errors.each do |error| %>
                          <li>
                            <%= error.full_message %>
                          </li>
                          <% end %>
                      </ul>
                    </div>
                    <% end %>
                      <%= form.hidden_field :user_id, value: tool.user_id %>
                        <%= form.hidden_field :content,
                          value: "#{current_user.name} has requested for the tool #{tool.toolname} you posted" %>
                          <%= form.hidden_field :status, value: "pending" %>
                            <%= form.hidden_field :task_id, value: "" %>
                              <%= form.hidden_field :tool_id, value: tool.id %>
                                <%= form.hidden_field :requester_id, value: current_user.id %>
                                  <div>
                                    <%= form.submit "Request" , class: 'btn btn-primary' %>
                                  </div>
                                  <% end %>
                                    <% end%>
                                      <%else%>

                                        <p class="text-danger"><strong>Tool is out of stock</strong></p>
                                        <%end%>
          </div>
        </div>
      </div>
      <% end %>
  </div>
</div>

app/views/tools/my_tools.html.erb
<div class="container" style="margin-top:100px">
  <div class="row">
    <% @mytools.each do |tool| %>
      <div class="col-md-4 mb-4">
        <div class="card" style="background-color: #D6E6D6; max-width: 500px; margin: 0 auto;">
          <div class="card-body">
            <h3 class="card-title">
              <%= tool.toolname %>
            </h3>
            <p class="card-text"><strong>Available From:</strong>
              <%= tool.fromdate %>
            </p>
            <p class="card-text"><strong>Available Till:</strong>
              <%= tool.todate %>
            </p>
            <p class="card-text"><strong>Number of Tools:</strong>
              <%= tool.no_tools %>
            </p>
            <p class="card-text"><strong>Cost:</strong> ₹<%= tool.cost %>
            </p>
              <p class="card-text"><strong>Location:</strong> ₹<%= tool.location %>
            </p>
            <a href="<%= tool_path(tool) %>" class="btn btn-primary">Show this tool</a>
          </div>
        </div>
      </div>
      <% end %>
  </div>
</div>

app/views/tools/new.html.erb
<%= render "form", tool: @tool %>

app/views/tools/show.html.erb
<div class="p-5 my-4 bg-body-tertiary rounded-3">
  <div class="container-fluid py-5 px-5 my-2 my-form">
    <h1 class="display-5 fw-bold text-success text-center">Tool Details</h1>
    <h3 class="card-title">
      <%= @tool.toolname %>
    </h3>
    <p class="card-text"><strong>Available From:</strong>
      <%= @tool.fromdate %>
    </p>
    <p class="card-text"><strong>Available Till:</strong>
      <%= @tool.todate %>
    </p>
    <p class="card-text"><strong>Number of Tools:</strong>
      <%= @tool.no_tools %>
    </p>
    <p class="card-text"><strong>Cost:</strong> ₹<%= @tool.cost %>
    </p>
      <p class="card-text"><strong>Location:</strong> <%= @tool.location %>
        </p>

    <div>
      <%= link_to "Edit this tool" , edit_tool_path(@tool) ,class:'btn btn-primary'%>
        <%= button_to "Destroy this tool" , @tool, method: :delete,class:'btn btn-danger mt-1' %>
    </div>
  </div>
</div>