config/routes.rb
Rails.application.routes.draw do
  resources :seeds
  resources :crops
  get 'trending/index'
  resources :infos
  resources :events

  root 'home#homepage'
  
  mount ActionCable.server => '/cable'

  resources :notifications

  resources :tools

  resources :tasks


  devise_for :users

  resources :users_profiles, only: [:edit, :update]
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get 'home/homepage'

  get '/about', to:'home#about'
  get '/myprofile', to:'users_profiles#show'

  get '/mylistings', to:'tasks#my_tasks'
  get '/mylistings1', to:'tools#my_tools'
 
  get '/search/results', to: 'search#results'

  get '/trending', to: 'trending#index'

 

  get '/calendar', to: 'events#new'

  get 'message/index'

  get 'listings/mylistings'



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/crop.rb
class Crop < ApplicationRecord
  belongs_to :user
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
end

app/models/info.rb
class Info < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :task,optional: true
  belongs_to :tool,optional: true


  def self.notice

    expiry_tools = Tool.where("todate = ?", Date.tomorrow)
  
    expiry_tools.each do |tool|

    requester = Notification.find_by(user_id: tool.user_id)


     Notification.create!(
        user_id: requester.requester_id,
        content: "#{tool.toolname} you borrowd needs to be returned tommorow.",
        status: "pending",
        tool_id: tool.id,
        requester_id: tool.user_id
      )
     
      Notification.create!(
        user_id: tool.user_id,
        content: "#{tool.toolname} you rented out needs to be collected tomorrow.",
        status: "pending",
        tool_id: tool.id,
        requester_id:requester.requester_id
      )

puts 'notification sent'
    
 
    end
  end

end

app/models/region.rb
class Region < ApplicationRecord
end

app/models/seed.rb
class Seed < ApplicationRecord
  belongs_to :user
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  has_many :notifications 
end

app/models/tool.rb
class Tool < ApplicationRecord
  belongs_to :user
  has_many :notifications 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   has_one_attached :profile_picture
   
has_many :tasks

has_many :tools

has_many :notifications

has_many :messages
has_many :events

has_many :seeds
has_many :crops

   validates :name, :email, :phone_number, presence: true
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  def mylistings
    @mytools = current_user.tools
    @mytasks = current_user.tasks
    @myseeds = current_user.seeds
    @mycrops = current_user.crops
  end
end

app/helpers/crops_helper.rb
module CropsHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/seeds_helper.rb
module SeedsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/views/listings/_mycrops.html.erb
<div class="container">
  <div class="row">
    <% @mycrops.each do |crop| %>
      <div class="col-md-4 mb-4">
        <div class="card" style="background-color: #D6E6D6; max-width: 500px; margin: 0 auto;">
          <div class="card-body">
            <h3 class="card-title">
              <%= crop.name %>
            </h3>
            <p class="card-text"><strong>Weight:</strong>
              <%= crop.weight %> kg
            </p>
            <p class="card-text"><strong>Cost:</strong> ₹<%= crop.cost %>
            </p> 
            <a href="<%= crop_path(crop) %>" class="btn btn-primary">View this Crop</a>
          </div>
        </div>  
      </div>
      <% end %>
  </div>
 
</div>

app/views/listings/_myseeds.html.erb
<div class="container">
  <div class="row">
    <% @myseeds.each do |seed| %>
      <div class="col-md-4 mb-4">
        <div class="card" style="background-color: #D6E6D6; max-width: 500px; margin: 0 auto;">
          <div class="card-body">
            <h3 class="card-title">
              <%= seed.name %>
            </h3>
            <p class="card-text"><strong>Weight:</strong>
              <%= seed.weight %> kg
            </p>
            <p class="card-text"><strong>Cost:</strong> ₹<%= seed.cost %>
            </p>
             <a href="<%= seed_path(seed) %>" class="btn btn-primary">View this Crop</a>
          </div>
        </div>
      </div>
      <% end %>
     
  </div>
   
</div>

app/views/listings/_mytasks.html.erb
<div class="container">
  <div class="row">
    <% @mytasks.each do |task| %>
      <div class="col-md-4 mb-4">
        <div class="card" style="background-color: #D6E6D6; max-width: 500px; margin: 0 auto;">
          <div class="card-body">
            <h3 class="card-title">
              <%= task.taskname %>
            </h3>
            <p class="card-text"><strong>Start Date:</strong>
              <%= task.startdate %>
            </p>
            <p class="card-text"><strong>End Date:</strong>
              <%= task.enddate %>
            </p>
            <p class="card-text"><strong>Compensation:</strong>
              <%= task.componsation %>
            </p>
            <p class="card-text"><strong>Location:</strong>
              <%= task.location %>
            </p>
            <p class="card-text"><strong>Description:</strong>
              <%= task.taskdesc %>
            </p>

            <p>
              <%= link_to "View this task" , task ,class:'btn btn-primary' %>
            </p>
          </div>
        </div>
      </div>
      <% end %>
  </div>
</div>

app/views/listings/_mytools.html.erb
<div class="container">
  <div class="row">
    <% @mytools.each do |tool| %>
      <div class="col-md-4 mb-4">
        <div class="card" style="background-color: #D6E6D6; max-width: 500px; margin: 0 auto;">
          <div class="card-body">
            <h3 class="card-title">
              <%= tool.toolname %>
            </h3>
            <p class="card-text"><strong>Available From:</strong>
              <%= tool.fromdate %>
            </p>
            <p class="card-text"><strong>Available Till:</strong>
              <%= tool.todate %>
            </p>
            <p class="card-text"><strong>Number of Tools:</strong>
              <%= tool.no_tools %>
            </p>
            <p class="card-text"><strong>Cost:</strong> ₹<%= tool.cost %>
            </p>
            <p class="card-text"><strong>Location:</strong><%= tool.location %>
            </p>
            <a href="<%= tool_path(tool) %>" class="btn btn-primary">View this tool</a>
          </div>
        </div>
      </div>
      <% end %>
  </div>
</div>

app/views/listings/mylistings.html.erb
<h1 class="display-5 fw-bold text-success text-center"> Tasks</h1>
<%= render 'listings/mytasks' %>
  <hr />
  <h1 class="display-5 fw-bold text-success text-center"> Tools</h1>
  <%= render 'listings/mytools' %>
 <hr />
 <h1 class="display-5 fw-bold text-success text-center"> Crops</h1>
  <%= render 'listings/mycrops' %>
   <hr />
 <h1 class="display-5 fw-bold text-success text-center">Seeds</h1>
  <%= render 'listings/myseeds' %>