config/routes.rb
Rails.application.routes.draw do
  resources :seeds
  resources :crops
  get 'trending/index'
  resources :infos
  resources :events

  root 'home#homepage'
  
  mount ActionCable.server => '/cable'

  resources :notifications

  resources :tools

  resources :tasks


  devise_for :users

  resources :users_profiles, only: [:edit, :update]
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get 'home/homepage'

  get '/about', to:'home#about'
  get '/myprofile', to:'users_profiles#show'

  get '/mylistings', to:'tasks#my_tasks'
  get '/mylistings1', to:'tools#my_tools'
 
  get '/search/results', to: 'search#results'

  get '/trending', to: 'trending#index'

 

  get '/calendar', to: 'events#new'

  get 'message/index'

  get 'listings/mylistings'



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/crop.rb
class Crop < ApplicationRecord
  belongs_to :user
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
end

app/models/info.rb
class Info < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :task,optional: true
  belongs_to :tool,optional: true


  def self.notice

    expiry_tools = Tool.where("todate = ?", Date.tomorrow)
  
    expiry_tools.each do |tool|

    requester = Notification.find_by(user_id: tool.user_id)


     Notification.create!(
        user_id: requester.requester_id,
        content: "#{tool.toolname} you borrowd needs to be returned tommorow.",
        status: "pending",
        tool_id: tool.id,
        requester_id: tool.user_id
      )
     
      Notification.create!(
        user_id: tool.user_id,
        content: "#{tool.toolname} you rented out needs to be collected tomorrow.",
        status: "pending",
        tool_id: tool.id,
        requester_id:requester.requester_id
      )

puts 'notification sent'
    
 
    end
  end

end

app/models/region.rb
class Region < ApplicationRecord
end

app/models/seed.rb
class Seed < ApplicationRecord
  belongs_to :user
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  has_many :notifications 
end

app/models/tool.rb
class Tool < ApplicationRecord
  belongs_to :user
  has_many :notifications 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   has_one_attached :profile_picture
   
has_many :tasks

has_many :tools

has_many :notifications

has_many :messages
has_many :events

has_many :seeds
has_many :crops

   validates :name, :email, :phone_number, presence: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :set_notification, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /notifications or /notifications.json

  def index
    @notifications = Notification.where(user_id: current_user.id)
    usernames = {}
    @notifications.each do |notification|
    @user = User.find_by(id: notification.requester_id)
      
    end
     
  end

  # GET /notifications/1 or /notifications/1.json
  def show
  end

  # GET /notifications/new
  def new
    @notification = Notification.new
  end

  # GET /notifications/1/edit
  def edit
  end

  # POST /notifications or /notifications.json
  def create
    @notification = Notification.new(notification_params)

    respond_to do |format|
      if @notification.save
        format.html { redirect_to notifications_url, notice: "Notification has been sent." }
        format.json { render :show, status: :created, location: @notification }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notifications/1 or /notifications/1.json
  def update
    respond_to do |format|
      if @notification.update(notification_params)
        if @notification.status =='accepted'
          tool = Tool.find_by(id: @notification.tool_id)
          if (tool.present? && tool.no_tools > 0)
            tool.decrement!(:no_tools)
          end
        end

        format.html { redirect_to notifications_url, notice: "Notification was successfully updated." }
        format.json { render :show, status: :ok, location: @notification }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1 or /notifications/1.json
  def destroy
    @notification.destroy

    respond_to do |format|
      format.html { redirect_to notifications_url, notice: "Notification was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      @notification = Notification.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def notification_params
      params.require(:notification).permit(:user_id, :content, :status, :task_id, :tool_id, :requester_id)
    end
end

app/helpers/crops_helper.rb
module CropsHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/seeds_helper.rb
module SeedsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/views/notifications/_form.html.erb
<%= form_with(model: notification) do |form| %>
  <% if notification.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
        <% notification.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_field :content %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>

  <div>
    <%= form.label :task_id, style: "display: block" %>
    <%= form.text_field :task_id %>
  </div>

  <div>
    <%= form.label :tool_id, style: "display: block" %>
    <%= form.text_field :tool_id %>
  </div>

  <div>
    <%= form.label :requester_id, style: "display: block" %>
    <%= form.text_field :requester_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/notifications/_notification.html.erb
<div id="<%= dom_id notification %>">
  <p>
    <strong>User:</strong>
    <%= notification.user_id %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= notification.content %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= notification.status %>
  </p>

  <p>
    <strong>Task:</strong>
    <%= notification.task_id %>
  </p>

  <p>
    <strong>Tool:</strong>
    <%= notification.tool_id %>
  </p>

  <p>
    <strong>Requester:</strong>
    <%= notification.requester_id %>
  </p>

</div>

app/views/notifications/edit.html.erb
<h1>Editing notification</h1>

<%= render "form", notification: @notification %>

<br>

<div>
  <%= link_to "Show this notification", @notification %> |
  <%= link_to "Back to notifications", notifications_path %>
</div>

app/views/notifications/index.html.erb
<%= stylesheet_link_tag "style_1" %>
<div class="p-5 my-4 bg-body-tertiary rounded-3">
  <div class="container-fluid py-5 px-5 my-2 my-form shadow-md" style="min-height: 600px">
    <h1 class="display-6 fw-bold text-success text-center">Notifications</h1>

    <% @notifications.each do |notification| %>
      <div class="container mt-4 py-2" id="notifications" style="background-color: #93ceb5; border-radius: 10px">
        <div class="d-flex justify-content-center align-items-center">
          <p class="fs-5 mt-1 ms-5">
            <%= notification.content %>
          </p>
          <button type="button" class="btn btn-primary ms-auto" data-bs-toggle="modal"
            data-bs-target="#exampleModal<%= notification.id %>">
            Details
          </button>
        </div>
      </div>

      <div class="modal fade" id="exampleModal<%= notification.id %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
          <div class="modal-content">
            <div class="modal-header">
              <h1 class="modal-title fs-5 ms-auto" id="exampleModalLabel">
                Notification Details
              </h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body text-center">
              <p>Requester Name: <%= @user.name %></p>
              <p>Email: <%= @user.email %></p>
              <p>Phone: <%= @user.phone_number %></p>
              <% if notification.status == "pending" %>
                <p class="text-warning">Status: <%= notification.status %></p>
                <div class="d-flex justify-content-center">
                  <%= form_with(model: notification, url: notification_path(notification), method: :patch) do |form| %>
                    <%= form.hidden_field :status, value: 'accepted' %>
                    <%= form.submit 'Accept', class: 'btn btn-success m-3' %>
                  <% end %>
                  <%= form_with(model: notification, url: notification_path(notification), method: :patch) do |form| %>
                    <%= form.hidden_field :status, value: 'rejected' %>
                    <%= form.submit 'Reject', class: 'btn btn-danger m-3' %>
                  <% end %>
                </div>
              <% elsif notification.status == "rejected" %>
                <p class="text-danger">Status: <%= notification.status %></p>
              <% else %>
                <p class="text-success">Status: <%= notification.status %></p>
              <% end %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/notifications/new.html.erb
<h1>New notification</h1>

<%= render "form", notification: @notification %>

<br>

<div>
  <%= link_to "Back to notifications", notifications_path %>
</div>

app/views/notifications/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @notification %>

<div>
  <%= link_to "Edit this notification", edit_notification_path(@notification) %> |
  <%= link_to "Back to notifications", notifications_path %>

  <%= button_to "Destroy this notification", @notification, method: :delete %>
</div>