config/routes.rb
Rails.application.routes.draw do
  resources :seeds
  resources :crops
  get 'trending/index'
  resources :infos
  resources :events

  root 'home#homepage'
  
  mount ActionCable.server => '/cable'

  resources :notifications

  resources :tools

  resources :tasks


  devise_for :users

  resources :users_profiles, only: [:edit, :update]
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get 'home/homepage'

  get '/about', to:'home#about'
  get '/myprofile', to:'users_profiles#show'

  get '/mylistings', to:'tasks#my_tasks'
  get '/mylistings1', to:'tools#my_tools'
 
  get '/search/results', to: 'search#results'

  get '/trending', to: 'trending#index'

 

  get '/calendar', to: 'events#new'

  get 'message/index'

  get 'listings/mylistings'



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/crop.rb
class Crop < ApplicationRecord
  belongs_to :user
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
end

app/models/info.rb
class Info < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :task,optional: true
  belongs_to :tool,optional: true


  def self.notice

    expiry_tools = Tool.where("todate = ?", Date.tomorrow)
  
    expiry_tools.each do |tool|

    requester = Notification.find_by(user_id: tool.user_id)


     Notification.create!(
        user_id: requester.requester_id,
        content: "#{tool.toolname} you borrowd needs to be returned tommorow.",
        status: "pending",
        tool_id: tool.id,
        requester_id: tool.user_id
      )
     
      Notification.create!(
        user_id: tool.user_id,
        content: "#{tool.toolname} you rented out needs to be collected tomorrow.",
        status: "pending",
        tool_id: tool.id,
        requester_id:requester.requester_id
      )

puts 'notification sent'
    
 
    end
  end

end

app/models/region.rb
class Region < ApplicationRecord
end

app/models/seed.rb
class Seed < ApplicationRecord
  belongs_to :user
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  has_many :notifications 
end

app/models/tool.rb
class Tool < ApplicationRecord
  belongs_to :user
  has_many :notifications 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   has_one_attached :profile_picture
   
has_many :tasks

has_many :tools

has_many :notifications

has_many :messages
has_many :events

has_many :seeds
has_many :crops

   validates :name, :email, :phone_number, presence: true
end

app/controllers/infos_controller.rb
class InfosController < ApplicationController
  before_action :set_info, only: %i[ show edit update destroy ]

  # GET /infos or /infos.json
  def index
    @infos = Info.all
  end

  # GET /infos/1 or /infos/1.json
  def show
  end

  # GET /infos/new
  def new
    @info = Info.new
  end

  # GET /infos/1/edit
  def edit
  end

  # POST /infos or /infos.json
  def create
    @info = Info.new(info_params)

    respond_to do |format|
      if @info.save
        format.html { redirect_to info_url(@info), notice: "Info was successfully created." }
        format.json { render :show, status: :created, location: @info }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /infos/1 or /infos/1.json
  def update
    respond_to do |format|
      if @info.update(info_params)
        format.html { redirect_to info_url(@info), notice: "Info was successfully updated." }
        format.json { render :show, status: :ok, location: @info }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /infos/1 or /infos/1.json
  def destroy
    @info.destroy

    respond_to do |format|
      format.html { redirect_to infos_url, notice: "Info was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_info
      @info = Info.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def info_params
      params.require(:info).permit(:news, :location, :title)
    end
end

app/helpers/crops_helper.rb
module CropsHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/seeds_helper.rb
module SeedsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/helpers/trending_helper.rb
module TrendingHelper
end

app/views/infos/_form.html.erb
<%= stylesheet_link_tag "style_1" %>

  <div class="p-5 my-4 bg-body-tertiary rounded-3">
    <div class="container-fluid py-5 px-5 my-2 my-form">
      <h1 class="display-5 fw-bold text-success text-center">Post Information</h1>

<%= form_with(model: info) do |form| %>
  <% if info.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(info.errors.count, "error") %> prohibited this info from being saved:</h2>

      <ul>
        <% info.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :title, style: "display: block",class: "form-label" %>
    <%= form.text_field :title,class: "form-control" %>
  </div>
 <div class="mb-3">
    <%= form.label :location, style: "display: block",class: "form-label" %>
    <%= form.text_field :location , class: "form-control"%>
  </div>
  <div class="mb-3">
    <%= form.label :news, style: "display: block" ,class: "form-label"%>
    <%= form.text_area :news , class: "form-control" %>
  </div>


  <div>
    <%= form.submit "POST" , class:"btn btn-success mt-2" %>
  </div>
<% end %>
      </div>
      </div>

app/views/infos/_info.html.erb
<div id="<%= dom_id info %>">
  <p>
    <strong>News:</strong>
    <%= info.news %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= info.location %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= info.title %>
  </p>

</div>

app/views/infos/edit.html.erb
<%= render "form", info: @info %>


<div>
  <%= link_to "Show this info", @info %> |
  <%= link_to "Back to infos", infos_path %>
</div>

app/views/infos/index.html.erb
<div class="container">
  <div class="row">
    <% @infos.each do |info| %>
      <div class="col-md-4 mb-4">
        <div class="card mt-4" style="background-color: #D6E6D6; max-width: 500px; margin: 0 auto;">
          <div class="card-body">
            <h3 class="card-title">
              <%= info.title %>
            </h3>
            <p class="card-text"><strong>Location:</strong>
              <%= info.location%>
            </p>
            <p class="card-text"><strong>News:</strong>
              <%= info.news %>
            </p>
              <a href="<%= info_path(info) %>" class="btn btn-primary">Edit This Post</a>
          </div>
        </div>
      </div>
      <% end %>
  </div>
</div>

app/views/infos/new.html.erb
<%= render "form", info: @info %>

app/views/infos/show.html.erb
<p style="color: green"><%= notice %></p>

  <div class="p-5 my-4 bg-body-tertiary rounded-3">
    <div class="container-fluid py-5 px-5 my-2 my-form">
      <h1 class="display-5 fw-bold text-success text-center">Post Information</h1>

      <p><strong>Title:</strong>
        <%= @info.title %>
      </p>
      <p><strong>Location:</strong>
        <%= @info.location %>
      </p>
      <p><strong>Information:</strong>
        <%= @info.news %>
      </p>
     <%= link_to "Edit this Post" , edit_info_path(@info), class: "btn btn-primary" %>
      <%= button_to "Delete this post" , @info, method: :delete, class: "btn btn-danger mt-1" %>
      </div>
      </div>